[package]
authors = ["Erik Johnston <erikj@matrix.org>"]
name = "rust-changelog"
version = "0.1.0"

[dependencies]
git2 = "0.6.4"
hyper = "0.10.9"
indicatif = "0.3.3"
quick-error = "1.2.0"
regex = "0.2.1"
reqwest = "0.5.2"
scoped-pool = "1.0.0"
serde = "0.9"
serde_derive = "0.9"
